import { BUSINESS_MODEL_GUIDED_PACKAGE } from './business-model-v2';
import type {
  JiuxuangeCase,
  JiuxuangeCaseFact,
  JiuxuangeCourseModule,
  JiuxuangeCoursePackage,
  JiuxuangeQuestionTemplate,
  JiuxuangeSourceRef,
} from './types';

const V2 = BUSINESS_MODEL_GUIDED_PACKAGE;

const BEE_SOURCE: Omit<JiuxuangeSourceRef, 'locator'> = {
  documentId: 'case-convenience-bee',
  title: '《便利蜂商业模式》',
  verificationStatus: 'verified',
  contentHash: 'sha256:b5162cb5d933e7160d8910b4bce66f9d09de0be8f59c82e4b4f18161eee854e3',
};

const FRESH_SOURCE: Omit<JiuxuangeSourceRef, 'locator'> = {
  documentId: 'case-fresh-grocery-models',
  title: '《生鲜零售行业商业模式对比》',
  verificationStatus: 'verified',
  contentHash: 'sha256:143d8f315ed246ca3224cc2b11f067476a519d3b12bbf3322d534298265a3a36',
};

function courseFact(
  id: string,
  text: string,
  source: Omit<JiuxuangeSourceRef, 'locator'>,
  locator: string,
  observedAt: string,
): JiuxuangeCaseFact {
  return {
    id,
    text,
    sourceKind: 'course_case',
    sourceRef: { ...source, locator },
    visibility: 'learner',
    verificationStatus: 'verified',
    confidence: 'high',
    observedAt,
  };
}

const convenienceBee: JiuxuangeCase = {
  id: 'convenience-bee-loop',
  title: '便利蜂：谁在做门店决策',
  mode: 'curated_case',
  availability: 'pilot',
  conceptIds: ['six-elements-overview', 'business-system', 'key-resources-capabilities'],
  facts: [
    courseFact(
      'bee-loop-f1',
      '便利蜂采集门店消费、生产、仓储运输、门店视频、天气和热点事件等数据，作为中央系统的输入。',
      BEE_SOURCE,
      'PDF第5页「数字化能力是基石」',
      '案例材料覆盖期：2016-2022',
    ),
    courseFact(
      'bee-loop-f2',
      '案例描述便利蜂由持续迭代的“中央大脑”进行决策，人类工作人员辅助执行。',
      BEE_SOURCE,
      'PDF第3页「中央大脑决策，店长/店员执行」',
      '案例材料覆盖期：2016-2022',
    ),
    courseFact(
      'bee-loop-f3',
      '商品订购由中央系统根据销售反馈和周期性综合数据制定门店生产排期，并自动下单采购。',
      BEE_SOURCE,
      'PDF第6页「全流程数字化管理」商品订购行',
      '案例材料覆盖期：2016-2022',
    ),
    courseFact(
      'bee-loop-f4',
      '门店操作系统根据库存和销售情况，每隔15分钟向店员派送新的生产任务。',
      BEE_SOURCE,
      'PDF第6页「全流程数字化管理」生产计划行',
      '案例材料覆盖期：2016-2022',
    ),
    courseFact(
      'bee-loop-f5',
      '案例称门店运营中的30多个常规检查项由机器自动完成，并对不规范操作进行预警。',
      BEE_SOURCE,
      'PDF第6页「全流程数字化管理」店员管理行',
      '案例材料覆盖期：2016-2022',
    ),
  ],
};

const freshTransfer: JiuxuangeCase = {
  id: 'fresh-grocery-transfer',
  title: '生鲜零售：前置仓与社区团购',
  mode: 'curated_case',
  availability: 'pilot',
  conceptIds: ['six-elements-overview', 'positioning', 'business-system', 'profit-model'],
  facts: [
    courseFact(
      'fresh-transfer-f1',
      '美团优选采用代销和社区自提，流量来自团长私域与互联网平台，业务覆盖物流和用户端。',
      FRESH_SOURCE,
      'PDF第22页「四种模式的对比——如何重构产业链」',
      '报告比较口径：2020-2021',
    ),
    courseFact(
      'fresh-transfer-f2',
      '叮咚买菜采用自营前置仓和骑手送货上门，依赖互联网流量，并覆盖上游供应链到用户履约。',
      FRESH_SOURCE,
      'PDF第22页「四种模式的对比——如何重构产业链」',
      '报告比较口径：2020-2021',
    ),
    courseFact(
      'fresh-transfer-f3',
      '社区团购以销定采、库存周转较高，报告认为部分存货风险被转移给供应商。',
      FRESH_SOURCE,
      'PDF第22页「四种模式的对比——如何重构产业链」风险点列',
      '报告比较口径：2020-2021',
    ),
    courseFact(
      'fresh-transfer-f4',
      '前置仓通常自建自营仓网，建仓投入和经营杠杆较高，并承担损耗、退货等存货风险。',
      FRESH_SOURCE,
      'PDF第22页「四种模式的对比——如何重构产业链」风险点列',
      '报告比较口径：2020-2021',
    ),
    courseFact(
      'fresh-transfer-f5',
      '报告列示美团优选平均客单价约15元，叮咚买菜客单价为61.7元。',
      FRESH_SOURCE,
      'PDF第23页「定量对比：目标人群差异」',
      '报告数据口径：2020-2021',
    ),
    courseFact(
      'fresh-transfer-f6',
      '报告估算社区团购仓配费用率通常不超过15%-20%，前置仓履约成本率通常约30%-40%。',
      FRESH_SOURCE,
      'PDF第24页「定量对比：成本利润拆解」',
      '报告数据口径：2020Q4-2021',
    ),
  ],
};

const scaffolds = (
  light: string,
  structure: string,
  factFocus: string,
): NonNullable<JiuxuangeQuestionTemplate['scaffolds']> => [
  { hintLevel: 1, prompt: light },
  { hintLevel: 2, prompt: structure },
  { hintLevel: 3, prompt: factFocus },
];

const modules: JiuxuangeCourseModule[] = [
  {
    id: 'learning-baseline',
    code: 'A',
    order: 1,
    title: '先留下你的判断',
    learningObjective: '在教学前保存学员判断商业模式的原始依据。',
    conceptIds: ['six-elements-overview'],
    caseIds: [],
    questionTemplateIds: ['loop-baseline'],
    evidenceRuleIds: ['baseline-capture'],
  },
  {
    id: 'learning-foundations',
    code: 'B',
    order: 2,
    title: '必知必会',
    learningObjective: '区分产品、收入与完整商业模式。',
    conceptIds: ['transaction-principle', 'six-elements-overview'],
    caseIds: [],
    questionTemplateIds: ['loop-must-know'],
    evidenceRuleIds: ['concept-expression'],
  },
  {
    id: 'case-convenience-bee-loop',
    code: 'C',
    order: 3,
    title: '便利蜂事实观察',
    learningObjective: '先观察事实并形成独立判断，再解锁课程解释。',
    conceptIds: ['business-system', 'key-resources-capabilities'],
    caseIds: ['convenience-bee-loop'],
    questionTemplateIds: ['loop-bee-observe', 'loop-bee-commit', 'loop-bee-compare'],
    evidenceRuleIds: ['fact-observation', 'case-fact-causality', 'comparison-attempt'],
  },
  {
    id: 'fresh-grocery-transfer',
    code: 'D',
    order: 4,
    title: '生鲜新情境迁移',
    learningObjective: '在未披露作者解释的新案例中形成独立迁移判断。',
    conceptIds: ['business-system', 'profit-model'],
    caseIds: ['fresh-grocery-transfer'],
    questionTemplateIds: ['loop-fresh-transfer'],
    evidenceRuleIds: ['case-fact-causality'],
  },
  {
    id: 'judgment-revision',
    code: 'E',
    order: 5,
    title: '修正最初判断',
    learningObjective: '比较教学前后判断，并说明修正依据。',
    conceptIds: ['six-elements-overview'],
    caseIds: [],
    questionTemplateIds: ['loop-revision'],
    evidenceRuleIds: ['judgment-revision'],
  },
  {
    id: 'learning-feedback',
    code: 'F',
    order: 6,
    title: '学习反馈',
    learningObjective: '生成可回到原始消息和案例事实的非分数反馈。',
    conceptIds: ['six-elements-overview'],
    caseIds: [],
    questionTemplateIds: ['loop-feedback'],
    evidenceRuleIds: ['feedback-acknowledgement'],
  },
];

export const BUSINESS_MODEL_LEARNING_LOOP_PACKAGE: JiuxuangeCoursePackage = {
  id: 'business-model',
  version: '5.0.0-learning-loop-pilot',
  releaseStatus: 'pilot_b_only',
  formalScoringEnabled: false,
  title: '商业模式大课',
  entryMode: 'learning-loop',
  modules,
  concepts: V2.concepts,
  cases: {
    [convenienceBee.id]: convenienceBee,
    [freshTransfer.id]: freshTransfer,
  },
  questionTemplates: {
    'loop-baseline': {
      id: 'loop-baseline',
      phase: 'ground',
      learningNodeId: 'baseline_capture',
      conceptIds: ['six-elements-overview'],
      prompt: '一家店的产品卖得很好，为什么还不能据此判断它的商业模式成立？',
      singleQuestion: true,
      evidenceRuleIds: ['baseline-capture'],
      factScope: 'none',
      teachingMode: 'question-first',
    },
    'loop-must-know': {
      id: 'loop-must-know',
      phase: 'ground',
      learningNodeId: 'must_know_instruction',
      conceptIds: ['transaction-principle', 'six-elements-overview'],
      prompt: '用你自己的话说，“卖什么”和“商业模式如何成立”最关键的区别是什么？',
      singleQuestion: true,
      evidenceRuleIds: ['concept-expression'],
      factScope: 'none',
      conceptNodeId: 'six-elements-overview',
      learningFragmentIds: ['transaction-principle-definition', 'six-elements-overview-definition'],
      teachingMode: 'explain-then-check',
      teachingText:
        '商业模式不等于产品，也不只是收入来源。它描述利益相关者之间如何交易、谁做什么、谁承担成本和风险，以及这套关系怎样持续创造和分配价值。',
      scaffolds: scaffolds(
        '先只比较两个对象：一个是产品，另一个是组织交易的方式，它们有什么不同？',
        '试着用“产品回答___，商业模式还要回答___”说一句，你会填什么？',
        '先看“谁参与、怎么协作、成本风险由谁承担”三个角度，你能指出其中一个区别吗？',
      ),
    },
    'loop-bee-observe': {
      id: 'loop-bee-observe',
      phase: 'ground',
      learningNodeId: 'bee_fact_observation',
      conceptIds: ['business-system'],
      caseId: convenienceBee.id,
      casePhase: 'blind',
      prompt: '只看观察卡，哪一条事实最能说明门店里“谁做决定”发生了变化？',
      singleQuestion: true,
      evidenceRuleIds: ['fact-observation'],
      factScope: 'case',
      teachingMode: 'question-first',
      scaffolds: scaffolds(
        '先选一条含有“系统”或“店员”的事实，你选哪一条？',
        '比较中央系统和门店员工的动作，哪一方在决定、哪一方在执行？',
        '请聚焦 [bee-loop-f2]，这条事实里决策动作属于谁？',
      ),
    },
    'loop-bee-commit': {
      id: 'loop-bee-commit',
      phase: 'judge',
      learningNodeId: 'bee_independent_commit',
      conceptIds: ['business-system', 'key-resources-capabilities'],
      caseId: convenienceBee.id,
      casePhase: 'commit',
      prompt: '这些事实重新分配了哪项决策权，并可能带来什么结果？',
      singleQuestion: true,
      evidenceRuleIds: ['case-fact-causality'],
      factScope: 'case',
      teachingMode: 'question-first',
      scaffolds: scaffolds(
        '先选一个决策动作，例如订货、生产或检查，你想分析哪一个？',
        '试着按“事实___说明决策从___转到___，因此可能___”完成一句，你会怎么说？',
        '请只引用 [bee-loop-f3] 或 [bee-loop-f4]，你能说明决策权变化可能影响什么吗？',
      ),
    },
    'loop-bee-compare': {
      id: 'loop-bee-compare',
      phase: 'compare',
      learningNodeId: 'bee_unlock_compare',
      conceptIds: ['business-system', 'key-resources-capabilities'],
      caseId: convenienceBee.id,
      casePhase: 'compare',
      prompt: '课程解释补充或改变了你原判断中的哪一处关系？',
      singleQuestion: true,
      evidenceRuleIds: ['comparison-attempt'],
      factScope: 'case',
      conceptNodeId: 'convenience-bee',
      learningFragmentIds: ['bianlifeng-analysis'],
      teachingMode: 'explain-then-check',
      teachingText:
        '你的原判断已经冻结。现在可以对照课程解释：便利蜂的变化不只是使用软件，而是把信息采集、算法决策和门店执行重新分工；规模扩张依赖这套关系持续运转。',
    },
    'loop-fresh-transfer': {
      id: 'loop-fresh-transfer',
      phase: 'test',
      learningNodeId: 'fresh_transfer',
      conceptIds: ['business-system', 'profit-model'],
      caseId: freshTransfer.id,
      prompt: '比较社区团购和前置仓，你认为哪项关系差异最可能改变履约成本，并依据哪两条事实？',
      singleQuestion: true,
      evidenceRuleIds: ['case-fact-causality'],
      factScope: 'case',
      teachingMode: 'question-first',
      scaffolds: scaffolds(
        '先比较“自提”和“送货上门”，你认为哪一项会改变最后一公里成本？',
        '从履约方式、库存责任、客单价中选两个连接起来，你会选哪两个？',
        '请聚焦 [fresh-transfer-f1]、[fresh-transfer-f2] 和 [fresh-transfer-f6]，哪种履约关系可能解释费用率差异？',
      ),
    },
    'loop-revision': {
      id: 'loop-revision',
      phase: 'reflect',
      learningNodeId: 'judgment_revision',
      conceptIds: ['six-elements-overview'],
      prompt:
        '回看最初判断和两个案例，现在你会怎样修正判断商业模式是否成立的方法，并依据什么事实？',
      singleQuestion: true,
      evidenceRuleIds: ['judgment-revision'],
      factScope: 'disclosed',
      teachingMode: 'question-first',
      scaffolds: scaffolds(
        '你最初更关注产品、收入还是关系结构，现在最想补充哪一项？',
        '试着用“我原来主要看___，现在还会看___，因为___”说一句，你会怎么填？',
        '请选择便利蜂或生鲜的一条事实，哪条事实最能支持你的修正？',
      ),
    },
    'loop-feedback': {
      id: 'loop-feedback',
      phase: 'reflect',
      learningNodeId: 'evidence_feedback',
      conceptIds: ['six-elements-overview'],
      prompt: '读完这次学习反馈后，你准备在下一次真实观察中先核对哪项关系？',
      singleQuestion: true,
      evidenceRuleIds: ['feedback-acknowledgement'],
      factScope: 'none',
      teachingMode: 'explain-then-check',
      teachingText: '系统正在根据你的原始判断、案例判断、迁移回答和修正依据生成非分数反馈。',
    },
  },
  evidenceRules: {
    'baseline-capture': {
      id: 'baseline-capture',
      description: '保存教学前原始判断，不评价对错。',
      requiredSignals: [],
      provenanceRequired: false,
    },
    'concept-expression': {
      id: 'concept-expression',
      description: '用自己的话区分产品与商业模式。',
      requiredSignals: ['own_words', 'distinction'],
      provenanceRequired: false,
    },
    'fact-observation': {
      id: 'fact-observation',
      description: '引用至少一条学员可见、已核验事实。',
      requiredSignals: ['fact_ref'],
      provenanceRequired: true,
    },
    'case-fact-causality': {
      id: 'case-fact-causality',
      description: '引用案例事实并说明关系变化可能导致的结果。',
      requiredSignals: ['fact_ref', 'causal_link'],
      provenanceRequired: true,
    },
    'comparison-attempt': {
      id: 'comparison-attempt',
      description: '比较自己的原判断与课程解释。',
      requiredSignals: ['own_words'],
      provenanceRequired: false,
    },
    'judgment-revision': {
      id: 'judgment-revision',
      description: '保留修正后的判断和修正依据。',
      requiredSignals: ['judgment_revision'],
      provenanceRequired: false,
    },
    'feedback-acknowledgement': {
      id: 'feedback-acknowledgement',
      description: '完成反馈阅读后的下一步选择。',
      requiredSignals: [],
      provenanceRequired: false,
    },
  },
  transferRules: [],
};
