import type {
  JiuxuangeConcept,
  JiuxuangeCoursePackage,
  JiuxuangeCourseModule,
  JiuxuangeSourceRef,
} from './types';
import { FIXED_ASSESSMENT_QUESTIONS } from '../assessment/questions';

const PRINCIPLES_SOURCE: JiuxuangeSourceRef = {
  documentId: 'principles-of-business-model',
  title: '《商业模式学原理》',
  locator: '第2-8章（课程负责人提供 Markdown，标题路径与原 PDF 页码待逐节复核）',
  verificationStatus: 'verified',
};

function concept(
  id: string,
  name: string,
  definition: string,
  distinctions: string[],
): JiuxuangeConcept {
  return {
    id,
    name,
    definition,
    distinctions,
    misconceptions: ['只罗列名词而不说明要素之间的关系'],
    applicationCriteria: ['用自己的话说明概念边界', '用事实说明要素间的因果联系'],
    sourceRefs: [PRINCIPLES_SOURCE],
  };
}

const BEE_SOURCE = {
  documentId: 'case-convenience-bee',
  title: '《便利蜂商业模式》',
  verificationStatus: 'verified' as const,
};
const FRESH_SOURCE = {
  documentId: 'case-fresh-grocery-models',
  title: '《生鲜零售行业商业模式对比》',
  verificationStatus: 'verified' as const,
};

export const BUSINESS_MODEL_GUIDED_PACKAGE: JiuxuangeCoursePackage = {
  id: 'business-model',
  version: '2.0.0-guided-course',
  releaseStatus: 'full',
  formalScoringEnabled: false,
  title: '商业模式大课',
  modules: [
    ...([
      [
        'transaction-principle',
        'A',
        1,
        '交易原理',
        '理解商业模式如何组织交易与价值交换',
        'transaction-principle',
        'q-transaction',
      ],
      [
        'six-elements-overview',
        'B',
        2,
        '六要素总览',
        '建立六要素之间相互作用的整体图景',
        'six-elements-overview',
        'q-overview',
      ],
      [
        'positioning',
        'C',
        3,
        '定位',
        '从交易主体、内容、方式和成本识别定位',
        'positioning',
        'q-positioning',
      ],
      [
        'business-system',
        'D',
        4,
        '业务系统',
        '判断构型、角色与关系如何共同创造价值',
        'business-system',
        'q-system',
      ],
      [
        'key-resources-capabilities',
        'E',
        5,
        '关键资源能力',
        '识别支撑业务系统的稀缺资源与能力',
        'key-resources-capabilities',
        'q-resources',
      ],
      [
        'profit-model',
        'F',
        6,
        '盈利模式',
        '解释收支来源、收支方式和定价方式的联动',
        'profit-model',
        'q-profit',
      ],
      [
        'cash-flow-enterprise-value',
        'G',
        7,
        '现金流结构与企业价值',
        '从现金流时序理解企业价值形成',
        'cash-flow-enterprise-value',
        'q-cash-value',
      ],
    ].map(([id, code, order, title, learningObjective, conceptId, questionId]) => ({
      id: String(id),
      code: code as 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G',
      order: Number(order),
      title: String(title),
      learningObjective: String(learningObjective),
      conceptIds: [String(conceptId)],
      caseIds: [],
      questionTemplateIds: [String(questionId)],
      evidenceRuleIds: ['concept-understanding'],
    })) as JiuxuangeCourseModule[]),
    {
      id: 'case-convenience-bee',
      code: 'H',
      order: 8,
      title: '便利蜂案例盲解',
      learningObjective: '先依据事实独立拆解便利蜂，再与作者判断比较。',
      conceptIds: ['six-elements-overview'],
      caseIds: ['convenience-bee'],
      questionTemplateIds: ['bee-blind', 'bee-commit', 'bee-unlock', 'bee-compare'],
      evidenceRuleIds: ['case-judgment'],
    },
    {
      id: 'case-fresh-grocery',
      code: 'I',
      order: 9,
      title: '生鲜零售模式比较',
      learningObjective: '比较多种模式并把判断迁移到新的项目。',
      conceptIds: ['six-elements-overview'],
      caseIds: ['fresh-grocery-comparison'],
      questionTemplateIds: ['fresh-blind', 'fresh-commit', 'fresh-unlock', 'fresh-compare'],
      evidenceRuleIds: ['case-judgment'],
    },
    {
      id: 'personal-assessment',
      code: 'J',
      order: 10,
      title: '个人学习成果测评',
      learningObjective: '用六道开放题呈现事实、概念、因果、反证和迁移能力。',
      conceptIds: ['six-elements-overview'],
      caseIds: [],
      questionTemplateIds: FIXED_ASSESSMENT_QUESTIONS.map((question) => question.id),
      evidenceRuleIds: ['assessment-response'],
    },
  ],
  concepts: {
    'transaction-principle': concept(
      'transaction-principle',
      '交易原理',
      '商业模式描述利益相关者之间围绕价值创造与分配形成的交易结构。',
      ['不是单笔买卖', '不仅是产品交换'],
    ),
    'six-elements-overview': concept(
      'six-elements-overview',
      '商业模式六要素',
      '从定位、业务系统、关键资源能力、盈利模式、现金流结构和企业价值理解价值创造与获取。',
      ['不是产品功能清单', '不是收入模式的同义词'],
    ),
    positioning: concept(
      'positioning',
      '定位',
      '定位是企业满足哪些利益相关者的什么需求以及采用何种交易方式。',
      ['包含内部与外部利益相关者', '交易成本属于定位判断'],
    ),
    'business-system': concept(
      'business-system',
      '业务系统',
      '业务系统由构型、角色和关系构成，描述业务活动如何连接。',
      ['构型不同于组织架构图', '关系不仅是合同关系'],
    ),
    'key-resources-capabilities': concept(
      'key-resources-capabilities',
      '关键资源能力',
      '支撑交易结构并难以被替代的资源与能力。',
      ['不是企业拥有的全部资源', '必须与业务系统相互匹配'],
    ),
    'profit-model': concept(
      'profit-model',
      '盈利模式',
      '盈利模式描述收入与支出的来源、方式及定价机制。',
      ['收入来源不等于完整盈利模式', '应同时观察成本结构'],
    ),
    'cash-flow-enterprise-value': concept(
      'cash-flow-enterprise-value',
      '现金流结构与企业价值',
      '现金流结构反映现金流入流出的组成与时序，企业价值是六要素运行的结果。',
      ['利润不等于现金流', '企业价值不是孤立终点'],
    ),
  },
  cases: {
    'convenience-bee': {
      id: 'convenience-bee',
      title: '便利蜂',
      mode: 'curated_case',
      availability: 'pilot',
      conceptIds: [
        'six-elements-overview',
        'positioning',
        'business-system',
        'key-resources-capabilities',
      ],
      facts: [
        [
          'bee-f1',
          '便利蜂在2017年开出首批5家门店，2018年超过100家，2019年超过1000家并进入8个城市。',
          'PDF第2页',
        ],
        [
          'bee-f2',
          '便利蜂采用由中央大脑进行数据分析和算法决策、门店员工执行的运营模式。',
          'PDF第3页',
        ],
        [
          'bee-f3',
          '案例将核心消费情境概括为15分钟步行范围与约15元客单价的高频即时需求。',
          'PDF第4页',
        ],
        ['bee-f4', '案例描述了自动订货、动态定价等由数据驱动的门店活动。', 'PDF第6-7页'],
      ].map(([id, text, locator]) => ({
        id,
        text,
        sourceKind: 'course_case' as const,
        sourceRef: { ...BEE_SOURCE, locator },
        visibility: 'learner' as const,
        verificationStatus: 'verified' as const,
        confidence: 'high' as const,
      })),
    },
    'fresh-grocery-comparison': {
      id: 'fresh-grocery-comparison',
      title: '生鲜零售行业模式比较',
      mode: 'curated_case',
      availability: 'pilot',
      conceptIds: ['six-elements-overview', 'positioning', 'business-system', 'profit-model'],
      facts: [
        [
          'fresh-f1',
          '材料将生鲜零售归纳为店仓一体、前置仓、平台到家和社区团购等模式。',
          'PDF第5页',
        ],
        [
          'fresh-f2',
          '材料以钱大妈、叮咚买菜和美团优选等案例呈现不同履约与获客结构。',
          'PDF第7-19页',
        ],
        [
          'fresh-f3',
          '不同模式在门店或仓网、配送时效、SKU组织和流量来源上存在明显差异。',
          'PDF第20-24页',
        ],
      ].map(([id, text, locator]) => ({
        id,
        text,
        sourceKind: 'course_case' as const,
        sourceRef: { ...FRESH_SOURCE, locator },
        visibility: 'learner' as const,
        verificationStatus: 'verified' as const,
        confidence: 'high' as const,
      })),
    },
  },
  questionTemplates: {
    'q-transaction': {
      id: 'q-transaction',
      phase: 'ground',
      conceptIds: ['transaction-principle'],
      conceptNodeId: 'transaction-principle',
      prompt: '用你自己的话说，商业模式为什么不只是企业卖什么？',
      singleQuestion: true,
      evidenceRuleIds: ['concept-understanding'],
    },
    'q-overview': {
      id: 'q-overview',
      phase: 'ground',
      conceptIds: ['six-elements-overview'],
      conceptNodeId: 'six-elements-overview',
      prompt: '六要素中哪两个要素最容易被误认为彼此独立？',
      singleQuestion: true,
      evidenceRuleIds: ['concept-understanding'],
    },
    'q-positioning': {
      id: 'q-positioning',
      phase: 'apply',
      conceptIds: ['positioning'],
      conceptNodeId: 'positioning',
      prompt: '判断一家企业的定位时，你会先核对哪类交易事实？',
      singleQuestion: true,
      evidenceRuleIds: ['concept-understanding'],
    },
    'q-system': {
      id: 'q-system',
      phase: 'apply',
      conceptIds: ['business-system'],
      conceptNodeId: 'business-system',
      prompt: '业务系统里的角色关系会怎样改变价值创造方式？',
      singleQuestion: true,
      evidenceRuleIds: ['concept-understanding'],
    },
    'q-resources': {
      id: 'q-resources',
      phase: 'judge',
      conceptIds: ['key-resources-capabilities'],
      conceptNodeId: 'key-resources-capabilities',
      prompt: '什么条件下，一项资源才算这个商业模式的关键资源？',
      singleQuestion: true,
      evidenceRuleIds: ['concept-understanding'],
    },
    'q-profit': {
      id: 'q-profit',
      phase: 'judge',
      conceptIds: ['profit-model'],
      conceptNodeId: 'profit-model',
      prompt: '为什么只知道收入来自哪里还不足以判断盈利模式？',
      singleQuestion: true,
      evidenceRuleIds: ['concept-understanding'],
    },
    'q-cash-value': {
      id: 'q-cash-value',
      phase: 'reflect',
      conceptIds: ['cash-flow-enterprise-value'],
      conceptNodeId: 'cash-flow-enterprise-value',
      prompt: '利润增长但现金持续流出时，你会怎样重新判断企业价值？',
      singleQuestion: true,
      evidenceRuleIds: ['concept-understanding'],
    },
    'bee-blind': {
      id: 'bee-blind',
      phase: 'ground',
      conceptIds: ['six-elements-overview'],
      caseId: 'convenience-bee',
      casePhase: 'blind',
      prompt: '只看已开放事实，你会怎样描述便利蜂最关键的商业模式特征？',
      singleQuestion: true,
      evidenceRuleIds: ['case-judgment'],
    },
    'bee-commit': {
      id: 'bee-commit',
      phase: 'judge',
      conceptIds: ['six-elements-overview'],
      caseId: 'convenience-bee',
      casePhase: 'commit',
      prompt: '在解锁作者分析前，你会用哪条事实锁定自己的独立判断？',
      singleQuestion: true,
      evidenceRuleIds: ['case-judgment'],
    },
    'bee-unlock': {
      id: 'bee-unlock',
      phase: 'judge',
      conceptIds: ['six-elements-overview'],
      caseId: 'convenience-bee',
      casePhase: 'unlock',
      prompt: '提交独立判断后，作者分析中哪一点最值得用来检验你的判断？',
      singleQuestion: true,
      evidenceRuleIds: ['case-judgment'],
    },
    'bee-compare': {
      id: 'bee-compare',
      phase: 'compare',
      conceptIds: ['six-elements-overview'],
      caseId: 'convenience-bee',
      casePhase: 'compare',
      prompt: '比较事实、你的判断和作者判断后，你会修正哪条因果关系？',
      singleQuestion: true,
      evidenceRuleIds: ['case-judgment'],
    },
    'fresh-blind': {
      id: 'fresh-blind',
      phase: 'ground',
      conceptIds: ['six-elements-overview'],
      caseId: 'fresh-grocery-comparison',
      casePhase: 'blind',
      prompt: '只看事实，几种生鲜模式最关键的结构差异是什么？',
      singleQuestion: true,
      evidenceRuleIds: ['case-judgment'],
    },
    'fresh-commit': {
      id: 'fresh-commit',
      phase: 'judge',
      conceptIds: ['six-elements-overview'],
      caseId: 'fresh-grocery-comparison',
      casePhase: 'commit',
      prompt: '在解锁作者分析前，你会依据哪组差异锁定自己的比较判断？',
      singleQuestion: true,
      evidenceRuleIds: ['case-judgment'],
    },
    'fresh-unlock': {
      id: 'fresh-unlock',
      phase: 'judge',
      conceptIds: ['six-elements-overview'],
      caseId: 'fresh-grocery-comparison',
      casePhase: 'unlock',
      prompt: '提交比较判断后，作者分析中哪项证据最能挑战你的原判断？',
      singleQuestion: true,
      evidenceRuleIds: ['case-judgment'],
    },
    'fresh-compare': {
      id: 'fresh-compare',
      phase: 'reflect',
      conceptIds: ['six-elements-overview'],
      caseId: 'fresh-grocery-comparison',
      casePhase: 'compare',
      prompt: '把比较结论迁移到你的项目时，你会先验证哪个条件？',
      singleQuestion: true,
      evidenceRuleIds: ['case-judgment'],
    },
    ...Object.fromEntries(
      FIXED_ASSESSMENT_QUESTIONS.map((question) => [
        question.id,
        {
          id: question.id,
          phase: 'reflect' as const,
          conceptIds: ['six-elements-overview'],
          prompt: question.prompt,
          singleQuestion: true,
          evidenceRuleIds: ['assessment-response'],
        },
      ]),
    ),
  },
  evidenceRules: {
    'concept-understanding': {
      id: 'concept-understanding',
      description: '用自己的话说明概念及边界。',
      requiredSignals: ['own_words', 'distinction'],
      provenanceRequired: false,
    },
    'case-judgment': {
      id: 'case-judgment',
      description: '引用案例事实形成因果判断并给出反证。',
      requiredSignals: ['fact_ref', 'causal_link', 'counterevidence'],
      provenanceRequired: true,
    },
    'assessment-response': {
      id: 'assessment-response',
      description: '保留开放题原始回答与证据来源。',
      requiredSignals: ['own_words'],
      provenanceRequired: false,
    },
  },
  transferRules: [],
};
