import type {
  JiuxuangeProjectCard,
  JiuxuangeProjectCardSourceRef,
  JiuxuangeProjectCardStatement,
  JiuxuangeProjectCardStatementKind,
  JiuxuangeProjectCardTopic,
} from './types';

const DOCUMENT_ID = 'mckess-business-model-assignment-v29';

function statement(
  id: string,
  kind: JiuxuangeProjectCardStatementKind,
  topic: JiuxuangeProjectCardTopic,
  text: string,
  page: number,
  locator: string,
  confidence: JiuxuangeProjectCardStatement['confidence'] = 'medium',
  observedPeriod?: string,
): JiuxuangeProjectCardStatement {
  const sourceRef: JiuxuangeProjectCardSourceRef = {
    documentId: DOCUMENT_ID,
    page,
    locator,
  };
  return {
    id,
    kind,
    topic,
    text,
    sourceRef,
    verificationStatus: 'draft',
    confidence,
    observedPeriod,
  };
}

export const mckessProjectCardV2: JiuxuangeProjectCard = {
  schemaVersion: 2,
  kind: 'project_card',
  id: 'project-card-mckess@1.1.0-draft',
  projectId: 'mckess-central-kitchen',
  groupId: 'shenyang-naniele',
  version: '1.1.0-draft',
  title: '麦客思中央厨房商业模式重构项目卡',
  status: 'draft',
  entryMethod: 'admin_import',
  ownerConfirmationStatus: 'pending',
  importRef: 'mckess-v29-development-fixture',
  informationAsOf: '2024-12-31',
  confidentiality: 'project_confidential',
  projectStatus: 'preparing',
  sourceDocument: {
    id: DOCUMENT_ID,
    fileName: '[V29终稿】沈阳班-拿捏了-商业模式作业-李当心.pdf',
    title: '麦客思食品商业模式分析',
    pageCount: 37,
    contentHash: 'sha256:c6c9e6ce2fa77a3d23ac2b98669dd8262cb8de4784051c6ad9e258286c26d376',
    sourceKind: 'learner_assignment',
    createdAt: '2025-09-13T08:12:40+08:00',
  },
  modules: [
    {
      id: 'identity_governance',
      title: '项目身份与治理',
      summary: '明确项目归属、信息时点、案主责任和披露边界。',
      fields: [
        {
          id: 'governance-project-name',
          label: '项目名称',
          value: '麦客思中央厨房商业模式重构',
          status: 'draft',
          modelPolicy: 'allow',
        },
        {
          id: 'governance-company-alias',
          label: '企业名称或案例别名',
          value: '麦客思中央厨房',
          status: 'draft',
          modelPolicy: 'allow',
          sourceStatementIds: ['fact-company-registration'],
        },
        {
          id: 'governance-owner',
          label: '案主',
          value: '待项目关系中 target_owner 学员确认',
          status: 'unknown',
          modelPolicy: 'block',
        },
        {
          id: 'governance-industry',
          label: '所属行业',
          value: '食品加工与中央厨房服务',
          status: 'draft',
          modelPolicy: 'allow',
          sourceStatementIds: ['fact-core-business'],
        },
        {
          id: 'governance-region',
          label: '主要经营区域',
          value: '抚顺及辽沈地区',
          status: 'draft',
          modelPolicy: 'allow',
          sourceStatementIds: ['fact-customer-and-region'],
        },
        {
          id: 'governance-stage',
          label: '企业发展阶段',
          value: '经营调整与增长验证期，待案主确认',
          status: 'unknown',
          modelPolicy: 'allow',
        },
        {
          id: 'governance-as-of',
          label: '信息截止日期',
          value: '2024-12-31',
          status: 'draft',
          modelPolicy: 'allow',
        },
        {
          id: 'governance-confidentiality',
          label: '保密等级',
          value: '项目组保密',
          status: 'draft',
          modelPolicy: 'block',
        },
      ],
    },
    {
      id: 'business_profile',
      title: '企业基本业务信息',
      summary: '用一张业务底图回答企业服务谁、如何交付以及如何获得收入。',
      fields: [
        {
          id: 'business-one-sentence',
          label: '一句话业务定义',
          value:
            '作业报告将企业描述为：面向区域餐饮 B 端客户，提供定制预制菜、半成品和成品，通过订单生产与配送获得产品销售收入。',
          status: 'draft',
          modelPolicy: 'allow',
          sourceStatementIds: [
            'fact-core-business',
            'fact-customer-and-region',
            'fact-transaction-process',
          ],
        },
        {
          id: 'business-products',
          label: '主要产品或服务',
          value: '预制菜、半成品、成品，以及原材料销售、仓储和配送。',
          status: 'draft',
          modelPolicy: 'allow',
          sourceStatementIds: ['fact-core-business'],
        },
        {
          id: 'business-customers',
          label: '主要客户',
          value: '区域内粤式茶餐厅、港式火锅店和中式酒楼等 B 端餐饮客户。',
          status: 'draft',
          modelPolicy: 'allow',
          sourceStatementIds: ['fact-customer-and-region'],
        },
        {
          id: 'business-value-proposition',
          label: '核心价值主张',
          value: '区域深耕与高定制化供应，属于作业组判断，待案主验证。',
          status: 'draft',
          modelPolicy: 'allow',
          sourceStatementIds: ['claim-regional-customization'],
        },
        {
          id: 'business-transaction',
          label: '主要交易方式',
          value: '客户下单，中央厨房生产并配送；客户预付，企业再组织生产。',
          status: 'draft',
          modelPolicy: 'allow',
          sourceStatementIds: ['fact-transaction-process', 'fact-payment-terms'],
        },
        {
          id: 'business-revenue',
          label: '收入来源',
          value: '原材料销售，以及半成品和成品销售。',
          status: 'draft',
          modelPolicy: 'allow',
          sourceStatementIds: ['fact-revenue-composition'],
        },
        {
          id: 'business-channels',
          label: '主要渠道',
          value: '当前以直接服务区域 B 端客户为主，具体获客渠道待案主补充。',
          status: 'unknown',
          modelPolicy: 'allow',
          sourceStatementIds: ['fact-customer-and-region'],
        },
        {
          id: 'business-partners',
          label: '关键合作方',
          value: '原材料供应商、配送与潜在冷链物流服务方。',
          status: 'draft',
          modelPolicy: 'allow',
          sourceStatementIds: ['fact-payment-terms', 'proposal-third-party-logistics'],
        },
        {
          id: 'business-capabilities',
          label: '关键资源与能力',
          value: '供应商网络、产品 SOP、配方储备、柔性生产、采购与库存管理。',
          status: 'draft',
          modelPolicy: 'allow',
          sourceStatementIds: ['fact-capability-base'],
        },
      ],
    },
    {
      id: 'operating_snapshot',
      title: '当前经营快照',
      summary: '只呈现支持本轮判断的经营轮廓，不把完整财务原文送入模型。',
      fields: [
        {
          id: 'snapshot-revenue',
          label: '当前营收规模',
          value: '2024 年约 150 万至 200 万元。',
          status: 'draft',
          modelPolicy: 'mask',
          sourceStatementIds: ['fact-financial-performance', 'fact-team-size'],
        },
        {
          id: 'snapshot-trend',
          label: '近一年营收趋势',
          value: '报告数据呈下降趋势，具体原因待核验。',
          status: 'draft',
          modelPolicy: 'allow',
          sourceStatementIds: ['fact-financial-performance'],
        },
        {
          id: 'snapshot-profit',
          label: '盈利状态',
          value: '2024 年报告值为微利，但作业中同时存在“当前亏损”判断。',
          status: 'draft',
          modelPolicy: 'mask',
          sourceStatementIds: [
            'fact-financial-performance',
            'claim-2024-profitable',
            'claim-current-loss',
          ],
        },
        {
          id: 'snapshot-cash-flow',
          label: '现金流方式',
          value: '客户预付款后生产；供应商约六成月结、四成现付。',
          status: 'draft',
          modelPolicy: 'mask',
          sourceStatementIds: ['fact-payment-terms'],
        },
        {
          id: 'snapshot-customer-structure',
          label: '主要客户结构',
          value: '以区域餐饮 B 端客户为主，客户集中度与复购数据待补充。',
          status: 'unknown',
          modelPolicy: 'allow',
          sourceStatementIds: ['fact-customer-and-region'],
        },
        {
          id: 'snapshot-team',
          label: '当前组织规模',
          value: '作业画布列示 9 人，待案主确认。',
          status: 'draft',
          modelPolicy: 'mask',
          sourceStatementIds: ['fact-team-size'],
        },
        {
          id: 'snapshot-delivery',
          label: '当前交付规模',
          value: '2024 年报告列示产能利用率约两成。',
          status: 'draft',
          modelPolicy: 'mask',
          sourceStatementIds: ['fact-capacity-utilization'],
        },
        {
          id: 'snapshot-bottleneck',
          label: '当前主要瓶颈',
          value: '获客、品类聚焦与闲置产能利用之间的因果关系尚未确认。',
          status: 'unknown',
          modelPolicy: 'allow',
          sourceStatementIds: [
            'fact-capacity-utilization',
            'claim-scale-insufficient',
            'claim-missing-marketing-role',
          ],
        },
        {
          id: 'snapshot-goal',
          label: '未来 12 个月目标',
          value: '待案主填写。',
          status: 'unknown',
          modelPolicy: 'block',
        },
      ],
    },
    {
      id: 'core_challenge',
      title: '本次项目核心问题',
      summary: '把泛化的增长诉求收敛为可选择、可验证的经营决策。',
      fields: [
        {
          id: 'challenge-question',
          label: '当前核心问题',
          value:
            '在现有产能利用率较低、客户拓展能力尚未验证的条件下，应先深耕区域定制 B 端，还是扩展 OEM、多品类与新渠道？',
          status: 'draft',
          modelPolicy: 'allow',
          sourceStatementIds: [
            'fact-capacity-utilization',
            'claim-missing-marketing-role',
            'proposal-broaden-offering',
          ],
        },
        {
          id: 'challenge-background',
          label: '问题背景',
          value: '营收波动、产能闲置与扩厂设想同时存在。',
          status: 'draft',
          modelPolicy: 'allow',
          sourceStatementIds: [
            'fact-financial-performance',
            'fact-capacity-utilization',
            'assumption-expansion-plan',
          ],
        },
        {
          id: 'challenge-decision',
          label: '希望形成的决策',
          value: '确定下一阶段优先客户、交易方式和增长验证顺序。',
          status: 'draft',
          modelPolicy: 'allow',
        },
        {
          id: 'challenge-horizon',
          label: '决策时间范围',
          value: '未来 12 个月，待案主确认。',
          status: 'unknown',
          modelPolicy: 'allow',
        },
        {
          id: 'challenge-constraints',
          label: '关键约束',
          value: '小团队、区域服务半径、获客能力、产能利用和现金投入。',
          status: 'draft',
          modelPolicy: 'allow',
          sourceStatementIds: [
            'fact-team-size',
            'fact-customer-and-region',
            'fact-capacity-utilization',
          ],
        },
        {
          id: 'challenge-options',
          label: '当前候选方案',
          value: '区域定制深耕；多品类扩张；OEM 代加工；经销与线上渠道。',
          status: 'draft',
          modelPolicy: 'allow',
          sourceStatementIds: [
            'proposal-broaden-offering',
            'proposal-build-marketing-center',
            'proposal-solution-provider',
          ],
        },
        {
          id: 'challenge-risk',
          label: '案主最担心的风险',
          value: '待案主填写，不由作业组或 Agent 代答。',
          status: 'unknown',
          modelPolicy: 'block',
        },
      ],
    },
    {
      id: 'facts_hypotheses_unknowns',
      title: '事实、判断、假设与未知项',
      summary: '四类信息保持物理分层，任何草案内容都不能自动升级为企业事实。',
      fields: [
        {
          id: 'evidence-reported',
          label: '作业报告陈述',
          value: '14 条，均保持 draft，等待案主逐条确认。',
          status: 'draft',
          modelPolicy: 'allow',
        },
        {
          id: 'evidence-claims',
          label: '作业组判断',
          value: '8 条，不作为已验证事实。',
          status: 'draft',
          modelPolicy: 'allow',
        },
        {
          id: 'evidence-hypotheses',
          label: '方案与预测假设',
          value: '12 条，需要补充支持证据、反对证据和验证方式。',
          status: 'draft',
          modelPolicy: 'allow',
        },
        {
          id: 'evidence-unknowns',
          label: '当前未知项',
          value:
            '客户集中度与复购、获客成本、订单毛利、换线损耗、冷链半径、扩厂必要性、案主风险偏好。',
          status: 'unknown',
          modelPolicy: 'allow',
        },
      ],
    },
    {
      id: 'enterprise_assets',
      title: '企业材料目录',
      summary: '只保存材料元数据和安全摘要，原始文件默认不进入外部模型。',
      fields: [
        {
          id: 'asset-assignment',
          label: '商业模式作业',
          value: '37 页小组作业；当前作为开发提取来源，不等同于案主核验材料。',
          status: 'draft',
          modelPolicy: 'block',
        },
        {
          id: 'asset-missing',
          label: '仍需补充材料',
          value: '客户结构、订单与毛利、产能口径、库存周转、组织分工和未来经营目标。',
          status: 'unknown',
          modelPolicy: 'block',
        },
      ],
    },
    {
      id: 'course_conclusions',
      title: '前序课程结论',
      summary: '课程结论按版本保存，可被后续课程挑战，但不得原地改写。',
      fields: [
        {
          id: 'conclusion-reviewed',
          label: '已审核课程结论',
          value: '暂无。',
          status: 'unknown',
          modelPolicy: 'allow',
        },
        {
          id: 'conclusion-draft',
          label: '商业模式课作业组初步结论',
          value: '当前可能不缺生产设施，主要待验证约束是客户规模、获客角色与可复制的区域交易结构。',
          status: 'draft',
          modelPolicy: 'allow',
          sourceStatementIds: [
            'fact-capacity-utilization',
            'claim-scale-insufficient',
            'claim-missing-marketing-role',
          ],
        },
      ],
    },
  ],
  analysisPath: [
    {
      id: 'transaction_map',
      title: '谁和谁交易',
      prompt: '先列出客户、麦客思、供应商和配送方之间的商品、服务与资金交换。',
      topics: ['customer', 'business_system'],
    },
    {
      id: 'positioning',
      title: '服务谁、解决什么问题',
      prompt: '区分购买者、使用者和决策者，并说明麦客思究竟替客户解决什么经营问题。',
      topics: ['customer', 'positioning'],
    },
    {
      id: 'business_system',
      title: '各主体如何协作',
      prompt: '沿着订单、生产、配送和结算，判断各主体的角色、责任和利益关系。',
      topics: ['business_system'],
    },
    {
      id: 'key_resources_capabilities',
      title: '企业必须擅长什么',
      prompt: '找出让当前交易结构成立、且难以被替代的关键资源与能力。',
      topics: ['key_resources_capabilities'],
    },
    {
      id: 'profit_model',
      title: '谁向谁付钱',
      prompt: '识别收入来源、定价单位、主要成本承担者及利益分配方式。',
      topics: ['profit_model'],
    },
    {
      id: 'cash_flow_structure',
      title: '钱在什么时候流入和占用',
      prompt: '比较预收、现付、月结、库存、设备和扩张投入对现金的影响。',
      topics: ['cash_flow_structure'],
    },
    {
      id: 'enterprise_value',
      title: '什么决定长期企业价值',
      prompt: '判断哪些能力能够被复制、持续产生自由现金流并降低增长风险。',
      topics: ['enterprise_value'],
    },
    {
      id: 'causal_map',
      title: '汇总六要素因果图',
      prompt: '把定位、业务系统、关键资源能力、盈利模式、现金流结构和企业价值连成因果链。',
      topics: [
        'positioning',
        'business_system',
        'key_resources_capabilities',
        'profit_model',
        'cash_flow_structure',
        'enterprise_value',
      ],
    },
  ],
  reportedFacts: [
    statement(
      'fact-company-registration',
      'reported_fact',
      'identity',
      '作业报告称，辽宁麦客思食品有限公司于2021年成立，注册资本300万元。',
      9,
      '企业介绍：成立时间与注册资本',
      'high',
      '2021',
    ),
    statement(
      'fact-site-scale',
      'reported_fact',
      'operations',
      '作业报告称，企业占地约5000平方米、厂区约8000平方米。',
      9,
      '企业介绍：占地与厂区规模',
      'medium',
    ),
    statement(
      'fact-independent-accounting',
      'reported_fact',
      'business_system',
      '作业报告称，中央厨房与直营门店采用独立核算。',
      9,
      '运营及发展历程',
      'high',
    ),
    statement(
      'fact-store-history',
      'reported_fact',
      'operations',
      '作业报告称，2022年直营与加盟门店合计达到9家；2023年开始控制成本并调整门店；2024年门店数量减少但经营面积不变。',
      9,
      '运营及发展历程',
      'medium',
      '2022-2024',
    ),
    statement(
      'fact-core-business',
      'reported_fact',
      'positioning',
      '核心业务是为B端餐饮客户定制预制菜、半成品和成品，示例产品包括虾饺和馅饼；辅助业务包括原材料销售、仓储与配送。',
      10,
      '企业主营业务与表现：核心业务与辅助业务',
      'high',
    ),
    statement(
      'fact-revenue-composition',
      'reported_fact',
      'profit_model',
      '报告列示的原材料收入分别为2022年60.0万元、2023年80.3万元、2024年52.9万元；半成品和成品收入分别为121.8万元、133.6万元、122.8万元。',
      10,
      '营业收入情况图',
      'high',
      '2022-2024',
    ),
    statement(
      'fact-capacity-utilization',
      'reported_fact',
      'operations',
      '报告列示麦客思2024年产能利用率为20.65%。',
      10,
      '产能利用率情况分析图',
      'high',
      '2024',
    ),
    statement(
      'fact-customer-and-region',
      'reported_fact',
      'customer',
      '当前主要服务对象被描述为抚顺及辽沈地区的粤式茶餐厅、港式火锅店和中式酒楼等B端客户。',
      14,
      '定位：代表客户与服务区域',
      'medium',
    ),
    statement(
      'fact-transaction-process',
      'reported_fact',
      'business_system',
      '当前业务系统被描述为以“订单—生产—配送”为核心。',
      16,
      '业务系统标题',
      'high',
    ),
    statement(
      'fact-payment-terms',
      'reported_fact',
      'cash_flow_structure',
      '报告称企业收到客户预付款后生产；原材料采购中约60%向供应商月结、40%现付。',
      19,
      '盈利模式：收入与支出方式',
      'medium',
    ),
    statement(
      'fact-capability-base',
      'reported_fact',
      'key_resources_capabilities',
      '报告将稳定供应商网络、当地品牌知名度、订单持续性、物流成本管控、产品SOP、配方技术储备、柔性生产、预算与采购成本控制、库存周转和先进先出列为已具备能力。',
      21,
      '关键资源能力：已具备项目',
      'medium',
    ),
    statement(
      'fact-financial-performance',
      'reported_fact',
      'cash_flow_structure',
      '报告列示营业收入为2022年181.8万元、2023年213.9万元、2024年175.7万元；净利润分别为-4.3万元、-9.1万元和2.0万元。',
      22,
      '营业收入分析图',
      'high',
      '2022-2024',
    ),
    statement(
      'fact-margin-performance',
      'reported_fact',
      'cash_flow_structure',
      '报告列示毛利率为2022年22.37%、2023年19.74%、2024年31.29%；净利润率分别为-2.38%、-4.26%和1.16%。',
      22,
      '利润率分析图',
      'high',
      '2022-2024',
    ),
    statement(
      'fact-team-size',
      'reported_fact',
      'operations',
      '商业模式画布将企业员工人数列为9人，营收规模列为150万至200万元。',
      35,
      '商业模式画布：企业背景资料',
      'medium',
    ),
  ],
  learnerClaims: [
    statement(
      'claim-2024-profitable',
      'learner_claim',
      'cash_flow_structure',
      '作业组判断，2024年成本控制开始见效，中央厨房开始盈利。',
      9,
      '企业介绍：运营及发展历程',
      'medium',
      '2024',
    ),
    statement(
      'claim-current-loss',
      'learner_claim',
      'cash_flow_structure',
      '作业组在市场分析中同时判断，企业当前客户数量逐年减少并处于亏损状态。',
      12,
      '标的企业市场分析：中央厨房',
      'medium',
    ),
    statement(
      'claim-regional-customization',
      'learner_claim',
      'positioning',
      '作业组将当前定位概括为“区域深耕+高定制化”，核心是粤式茶点研发、生产加工与供应服务。',
      14,
      '定位：市场与产品战略定位',
      'medium',
    ),
    statement(
      'claim-largest-local-supplier',
      'learner_claim',
      'positioning',
      '作业组称麦客思是抚顺及周边粤式餐品餐厅的最大供货商。',
      14,
      '定位：满足客户需求方式',
      'low',
    ),
    statement(
      'claim-scale-insufficient',
      'learner_claim',
      'business_system',
      '作业组判断，下游客户规模不足，使集中采购、集约排产和研发复制等模式红利尚未得到验证。',
      15,
      '定位：存在问题',
      'medium',
    ),
    statement(
      'claim-missing-marketing-role',
      'learner_claim',
      'business_system',
      '作业组判断，当前业务系统缺少专业营销中心和持续拓展B端客户、协调上下游议价的角色。',
      16,
      '业务系统：存在问题',
      'medium',
    ),
    statement(
      'claim-single-income-source',
      'learner_claim',
      'profit_model',
      '作业组判断，企业收入主要依赖B端客户产品采购，收入来源单一且风险较高。',
      19,
      '盈利模式：分析',
      'medium',
    ),
    statement(
      'claim-low-financial-leverage',
      'learner_claim',
      'cash_flow_structure',
      '作业组判断，公司财务杠杆接近零，当前财务策略保守且安全。',
      23,
      '现金流结构：财务性杠杆',
      'low',
    ),
  ],
  redesignProposals: [
    statement(
      'proposal-broaden-offering',
      'redesign_proposal',
      'positioning',
      '在粤式菜品基础上扩充产品组合，并增加分销合作、食品创业者解决方案和OEM代加工。',
      33,
      '总结建议：定位调整',
      'medium',
    ),
    statement(
      'proposal-build-marketing-center',
      'redesign_proposal',
      'business_system',
      '内部建立营销中心，外部连接线下经销商和线上销售商，形成整体销售体系并建设自有品牌。',
      33,
      '总结建议：业务系统调整',
      'medium',
    ),
    statement(
      'proposal-diversify-customers',
      'redesign_proposal',
      'customer',
      '从只服务粤点客户转向多类型B端客户，并增加代加工客户、食品经销商和线上零售渠道。',
      33,
      '总结建议：关键资源能力调整',
      'medium',
    ),
    statement(
      'proposal-third-party-logistics',
      'redesign_proposal',
      'key_resources_capabilities',
      '引入第三方冷链物流资源，强化配送能力并扩大服务半径。',
      33,
      '总结建议：关键资源能力调整',
      'medium',
    ),
    statement(
      'proposal-incentive-model',
      'redesign_proposal',
      'profit_model',
      '将内部生产利益相关者的盈利方式调整为“固定+分成”，以提升生产意愿和效率。',
      33,
      '总结建议：盈利结构调整',
      'low',
    ),
    statement(
      'proposal-solution-provider',
      'redesign_proposal',
      'positioning',
      '长期方向是从区域粤式茶点外包商转型为生产、OEM、物流配送和解决方案一体化的区域中央厨房服务商。',
      35,
      '商业模式画布：商业模式定位',
      'medium',
    ),
  ],
  forecastAssumptions: [
    statement(
      'assumption-expansion-plan',
      'forecast_assumption',
      'operations',
      '报告预计2026年厂区扩建至2万余平方米。',
      9,
      '企业介绍：扩厂计划',
      'low',
      '2026',
    ),
    statement(
      'assumption-marginal-profit',
      'forecast_assumption',
      'cash_flow_structure',
      '作业组假设，新增客户利用闲置产能后，新增销售额除原材料外的边际成本很低，可大幅转化为利润。',
      23,
      '现金流结构：上行潜力',
      'low',
    ),
    statement(
      'assumption-2026-revenue',
      'forecast_assumption',
      'enterprise_value',
      '估值模型假设2026年底营业收入达到250万元。',
      24,
      '企业价值：假设02',
      'low',
      '2026',
    ),
    statement(
      'assumption-utilization-and-margin',
      'forecast_assumption',
      'enterprise_value',
      '估值模型假设生产效率从当前60%提升到90%，2027年净利润率达到10%。',
      24,
      '企业价值：假设02',
      'low',
      '2027',
    ),
    statement(
      'assumption-growth-rate',
      'forecast_assumption',
      'enterprise_value',
      '估值模型采用14%的企业年增长率。',
      24,
      '企业价值：假设03',
      'low',
    ),
    statement(
      'assumption-valuation',
      'forecast_assumption',
      'enterprise_value',
      '估值模型采用11.5%的折现率、2%的永续增长率和92.8万元永续现金流，计算企业估值为752.8万元。',
      24,
      '企业价值：估值参数与结果',
      'low',
    ),
  ],
  tensions: [
    {
      id: 'tension-profit-status',
      title: '2024盈利与“当前亏损”同时出现',
      statementIds: ['claim-2024-profitable', 'claim-current-loss'],
      prompt: '这两个判断是否处于同一口径和同一时间点？你需要补充什么数据才能判断？',
      status: 'open',
    },
    {
      id: 'tension-capacity-baseline',
      title: '产能利用率基线不一致',
      statementIds: ['fact-capacity-utilization', 'assumption-utilization-and-margin'],
      prompt: '报告同时出现两种差异显著的利用率基线，哪一个对应产能利用率，哪一个可能是生产效率？',
      status: 'open',
    },
    {
      id: 'tension-expansion-versus-idle-capacity',
      title: '低利用率与扩厂计划并存',
      statementIds: ['fact-capacity-utilization', 'assumption-expansion-plan'],
      prompt: '在现有产能利用率较低时扩厂，需要什么订单、品类或设备约束证据才能成立？',
      status: 'open',
    },
    {
      id: 'tension-focus-versus-diversification',
      title: '区域粤点深耕与多品类扩张',
      statementIds: ['claim-regional-customization', 'proposal-broaden-offering'],
      prompt: '多品类扩张是在强化现有定位，还是改变定位？判断依据是什么？',
      status: 'open',
    },
    {
      id: 'tension-capability-versus-strategy',
      title: '营销能力缺口与增长方案',
      statementIds: ['claim-missing-marketing-role', 'proposal-diversify-customers'],
      prompt: '在营销角色尚未建立时，多客户、多渠道方案最先会卡在哪个交易环节？',
      status: 'open',
    },
  ],
  agentPolicies: [
    {
      agentId: 'professor',
      purpose: '把已经讲授的六要素概念带回项目，但不使用项目卡替代教材。',
      allowedStatementKinds: ['reported_fact', 'learner_claim'],
      must: [
        '明确区分报告事实与作业组判断',
        '一次只提出一个概念应用问题',
        '引用statement id保留证据来源',
      ],
      mustNot: [
        '把项目卡作为商业模式概念的权威来源',
        '把草案事实说成已经核验',
        '直接认可作业组的最终方案',
      ],
    },
    {
      agentId: 'senior',
      purpose: '用项目事实和矛盾点陪学员练习六要素判断与修正。',
      allowedStatementKinds: [
        'reported_fact',
        'learner_claim',
        'redesign_proposal',
        'forecast_assumption',
      ],
      must: [
        '先确认学员引用的是事实、主张还是假设',
        '学员说不知道时提供事实聚焦支架并继续推进',
        '引导学员给出因果关系和反证条件',
      ],
      mustNot: [
        '直接给出项目应采用的商业模式',
        '把小组建议称为标准答案',
        '因为非标准回答而让学习停滞',
      ],
    },
    {
      agentId: 'mystery',
      purpose: '扮演客户、经销商、供应商、物流方或投资人，对方案进行情境对抗。',
      allowedStatementKinds: [
        'reported_fact',
        'learner_claim',
        'redesign_proposal',
        'forecast_assumption',
      ],
      must: ['声明当前扮演的利益相关者', '围绕一个开放矛盾追问', '要求学员指出成立条件或失败信号'],
      mustNot: [
        '虚构项目卡没有提供的新事实',
        '一次同时扮演多个利益相关者',
        '泄露后台证据或评分结构',
      ],
    },
    {
      agentId: 'growth_feedback',
      purpose: '回放学员判断如何从初始观点修正为有事实依据的观点。',
      allowedStatementKinds: [
        'reported_fact',
        'learner_claim',
        'redesign_proposal',
        'forecast_assumption',
      ],
      must: [
        '分别引用学员原判断、修正后判断和项目卡证据',
        '标记自主发现与提示后发现',
        '指出仍待项目方核验的问题',
      ],
      mustNot: [
        '生成未经人工校准的正式数字分数',
        '把对话时长当成学习质量',
        '把未核验陈述升级为事实',
      ],
    },
  ],
};
